### ISSUE TITLE
wintab update introduced new issue

### ISSUE THREAD

**Issue by dliston** [isolver/psychopy#31]
hi sol, 

hope all is well with you. 

one of the changes yesterday might have introduced a linux-specific issue, as we haven't seen it before and it seems to be new as of yesterday.  here's the output from the iohub keyboard demo, running on ubuntu using the environment :

(PYDEV)cobra@COBRA-A:~/DEV/appliance/install/psychopy/psychopy/demos/coder/iohub$ python keyboard.py
Traceback (most recent call last):
  File "keyboard.py", line 11, in <module>
    from psychopy.iohub import launchHubServer
  File "/home/cobra/PYDEV/local/lib/python2.7/site-packages/PsychoPy-1.83.1-py2.7.egg/psychopy/iohub/**init**.py", line 75, in <module>
    import client
  File "/home/cobra/PYDEV/local/lib/python2.7/site-packages/PsychoPy-1.83.1-py2.7.egg/psychopy/iohub/client/**init**.py", line 2116, in <module>
    import wintabtablet
  File "/home/cobra/PYDEV/local/lib/python2.7/site-packages/PsychoPy-1.83.1-py2.7.egg/psychopy/iohub/client/wintabtablet.py", line 14, in <module>
    from win32api import LOWORD, HIWORD
ImportError: No module named win32api

thanks for taking a look at this.

best,
dorion

**Comment by isolver** [comment]
Thanks for pointing this out. I'll fix it tomorrow and do a commit.

**Comment by isolver** [comment]
Can you get the latest source and let me know if the issue is fixed for
linux? Sorry, too busy right now to test myself. ;(

**Comment by dliston** [comment]
Sure, we'll test it today.

**Comment by dliston** [comment]
Tested the new psychopy. Everything works!


Thanks,
Lily

**Comment by isolver** [comment]
Great. Thank you for testing it and letting me know.
